### PR TITLE
Add insightface new

### PR DESCRIPTION
**Pull request by AndreaMacarulla**
Insightface toevoegen

### CODE REVIEW

**Comment by JeroenMandersloot** [comment]
Building the docker image works fine. But when I try to run it and then inside the container run `python run.py` I get the following error:

```
Trained model will be downloaded.../LR-face/insightface/models/model-r100-ii
Traceback (most recent call last):
  File "run.py", line 13, in <module>
    from lr_face.experiment_settings import ExperimentSettings
  File "/LR-face/lr_face/experiment_settings.py", line 3, in <module>
    from params import *
  File "/LR-face/params.py", line 12, in <module>
    from insightface.deploy import ArcFace
  File "/LR-face/insightface/deploy/ArcFace.py", line 33, in <module>
    with open(zip_file, "wb") as f :
FileNotFoundError: [Errno 2] No such file or directory: '/LR-face/insightface/models/model-r100-ii.zip'
```

**Comment by AndreaMacarulla** [comment]
> > Building the docker image works fine. But when I try to run it and then inside the container run `python run.py` I get the following error:
> > ```
> > Trained model will be downloaded.../LR-face/insightface/models/model-r100-ii
> > Traceback (most recent call last):
> >   File "run.py", line 13, in <module>
> >     from lr_face.experiment_settings import ExperimentSettings
> >   File "/LR-face/lr_face/experiment_settings.py", line 3, in <module>
> >     from params import *
> >   File "/LR-face/params.py", line 12, in <module>
> >     from insightface.deploy import ArcFace
> >   File "/LR-face/insightface/deploy/ArcFace.py", line 33, in <module>
> >     with open(zip_file, "wb") as f :
> > FileNotFoundError: [Errno 2] No such file or directory: '/LR-face/insightface/models/model-r100-ii.zip'
> > ```
> 
> Ah sorry! I forgot to add an empty folder insightface/models/ for the script to download the model there. I added it now to the add-insightface-new branch. Can you rebuild the image and see if it works now?


Or to test faster you can also do inside the container '$cd insightface' and '$mkdir models'.

**Comment by JeroenMandersloot** [comment]
I fixed the previous error but now I get an error related to the GPU, see below:

```
Traceback (most recent call last):
  File "run.py", line 79, in <module>
    run(arg)
  File "run.py", line 49, in run
    make_plots_and_save_as=make_plots_and_save_as)
  File "run.py", line 69, in experiment
    p = lr_system.scorer.predict_proba(data_provider.X_calibrate, data_provider.ids_calibrate)
  File "/LR-face/lr_face/models.py", line 79, in predict_proba
    score = self.score_for_pair(pair)
  File "/LR-face/lr_face/models.py", line 86, in score_for_pair
    img1_adapted = self.model.get_input(np.array(pair[0]))
  File "/LR-face/insightface/deploy/face_model.py", line 71, in get_input
    ret = self.detector.detect_face(face_img, det_type = self.args.det)
  File "/LR-face/insightface/deploy/mtcnn_detector.py", line 413, in detect_face
    output = self.RNet.predict(input_buf)
  File "/miniconda/envs/LRface/lib/python3.7/site-packages/mxnet/model.py", line 736, in predict
    o_list.append(o_nd[0:real_size].asnumpy())
  File "/miniconda/envs/LRface/lib/python3.7/site-packages/mxnet/ndarray/ndarray.py", line 2535, in asnumpy
    ctypes.c_size_t(data.size)))
  File "/miniconda/envs/LRface/lib/python3.7/site-packages/mxnet/base.py", line 255, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [07:22:14] src/operator/nn/./cudnn/cudnn_convolution-inl.h:155: Check failed: e == CUDNN_STATUS_SUCCESS (8 vs. 0) : cuDNN: CUDNN_STATUS_EXECUTION_FAILED
Stack trace:
  [bt] (0) /miniconda/envs/LRface/lib/python3.7/site-packages/mxnet/libmxnet.so(+0x6b41eb) [0x7f73e04301eb]
  [bt] (1) /miniconda/envs/LRface/lib/python3.7/site-packages/mxnet/libmxnet.so(+0x459d9bb) [0x7f73e43199bb]
  [bt] (2) /miniconda/envs/LRface/lib/python3.7/site-packages/mxnet/libmxnet.so(+0x45c6a59) [0x7f73e4342a59]
  [bt] (3) /miniconda/envs/LRface/lib/python3.7/site-packages/mxnet/libmxnet.so(+0x37d69b9) [0x7f73e35529b9]
  [bt] (4) /miniconda/envs/LRface/lib/python3.7/site-packages/mxnet/libmxnet.so(+0x37e333a) [0x7f73e355f33a]
  [bt] (5) /miniconda/envs/LRface/lib/python3.7/site-packages/mxnet/libmxnet.so(+0x37bf6d1) [0x7f73e353b6d1]
  [bt] (6) /miniconda/envs/LRface/lib/python3.7/site-packages/mxnet/libmxnet.so(+0x37c2c10) [0x7f73e353ec10]
  [bt] (7) /miniconda/envs/LRface/lib/python3.7/site-packages/mxnet/libmxnet.so(+0x37c2ea6) [0x7f73e353eea6]
  [bt] (8) /miniconda/envs/LRface/lib/python3.7/site-packages/mxnet/libmxnet.so(+0x37bde84) [0x7f73e3539e84]
```

**Comment by JeroenMandersloot** [comment]
> I fixed the previous error but now I get an error related to the GPU, see below:
> 
> ```
> Traceback (most recent call last):
>   File "run.py", line 79, in <module>
>     run(arg)
>   File "run.py", line 49, in run
>     make_plots_and_save_as=make_plots_and_save_as)
>   File "run.py", line 69, in experiment
>     p = lr_system.scorer.predict_proba(data_provider.X_calibrate, data_provider.ids_calibrate)
>   File "/LR-face/lr_face/models.py", line 79, in predict_proba
>     score = self.score_for_pair(pair)
>   File "/LR-face/lr_face/models.py", line 86, in score_for_pair
>     img1_adapted = self.model.get_input(np.array(pair[0]))
>   File "/LR-face/insightface/deploy/face_model.py", line 71, in get_input
>     ret = self.detector.detect_face(face_img, det_type = self.args.det)
>   File "/LR-face/insightface/deploy/mtcnn_detector.py", line 413, in detect_face
>     output = self.RNet.predict(input_buf)
>   File "/miniconda/envs/LRface/lib/python3.7/site-packages/mxnet/model.py", line 736, in predict
>     o_list.append(o_nd[0:real_size].asnumpy())
>   File "/miniconda/envs/LRface/lib/python3.7/site-packages/mxnet/ndarray/ndarray.py", line 2535, in asnumpy
>     ctypes.c_size_t(data.size)))
>   File "/miniconda/envs/LRface/lib/python3.7/site-packages/mxnet/base.py", line 255, in check_call
>     raise MXNetError(py_str(_LIB.MXGetLastError()))
> mxnet.base.MXNetError: [07:22:14] src/operator/nn/./cudnn/cudnn_convolution-inl.h:155: Check failed: e == CUDNN_STATUS_SUCCESS (8 vs. 0) : cuDNN: CUDNN_STATUS_EXECUTION_FAILED
> Stack trace:
>   [bt] (0) /miniconda/envs/LRface/lib/python3.7/site-packages/mxnet/libmxnet.so(+0x6b41eb) [0x7f73e04301eb]
>   [bt] (1) /miniconda/envs/LRface/lib/python3.7/site-packages/mxnet/libmxnet.so(+0x459d9bb) [0x7f73e43199bb]
>   [bt] (2) /miniconda/envs/LRface/lib/python3.7/site-packages/mxnet/libmxnet.so(+0x45c6a59) [0x7f73e4342a59]
>   [bt] (3) /miniconda/envs/LRface/lib/python3.7/site-packages/mxnet/libmxnet.so(+0x37d69b9) [0x7f73e35529b9]
>   [bt] (4) /miniconda/envs/LRface/lib/python3.7/site-packages/mxnet/libmxnet.so(+0x37e333a) [0x7f73e355f33a]
>   [bt] (5) /miniconda/envs/LRface/lib/python3.7/site-packages/mxnet/libmxnet.so(+0x37bf6d1) [0x7f73e353b6d1]
>   [bt] (6) /miniconda/envs/LRface/lib/python3.7/site-packages/mxnet/libmxnet.so(+0x37c2c10) [0x7f73e353ec10]
>   [bt] (7) /miniconda/envs/LRface/lib/python3.7/site-packages/mxnet/libmxnet.so(+0x37c2ea6) [0x7f73e353eea6]
>   [bt] (8) /miniconda/envs/LRface/lib/python3.7/site-packages/mxnet/libmxnet.so(+0x37bde84) [0x7f73e3539e84]
> ```

Possibly relevant: I have an RTX 2070 GPU, so I'm not sure if MXNet supports this already? Maybe not, as this seems to be an outdated MXNet version that requires Cuda 9.

Do you have access to the DGX station Andrea? If so, could you try running your docker container there?

**Comment by AndreaMacarulla** [comment]
> > I fixed the previous error but now I get an error related to the GPU, see below:
> > ```
> > Traceback (most recent call last):
> >   File "run.py", line 79, in <module>
> >     run(arg)
> >   File "run.py", line 49, in run
> >     make_plots_and_save_as=make_plots_and_save_as)
> >   File "run.py", line 69, in experiment
> >     p = lr_system.scorer.predict_proba(data_provider.X_calibrate, data_provider.ids_calibrate)
> >   File "/LR-face/lr_face/models.py", line 79, in predict_proba
> >     score = self.score_for_pair(pair)
> >   File "/LR-face/lr_face/models.py", line 86, in score_for_pair
> >     img1_adapted = self.model.get_input(np.array(pair[0]))
> >   File "/LR-face/insightface/deploy/face_model.py", line 71, in get_input
> >     ret = self.detector.detect_face(face_img, det_type = self.args.det)
> >   File "/LR-face/insightface/deploy/mtcnn_detector.py", line 413, in detect_face
> >     output = self.RNet.predict(input_buf)
> >   File "/miniconda/envs/LRface/lib/python3.7/site-packages/mxnet/model.py", line 736, in predict
> >     o_list.append(o_nd[0:real_size].asnumpy())
> >   File "/miniconda/envs/LRface/lib/python3.7/site-packages/mxnet/ndarray/ndarray.py", line 2535, in asnumpy
> >     ctypes.c_size_t(data.size)))
> >   File "/miniconda/envs/LRface/lib/python3.7/site-packages/mxnet/base.py", line 255, in check_call
> >     raise MXNetError(py_str(_LIB.MXGetLastError()))
> > mxnet.base.MXNetError: [07:22:14] src/operator/nn/./cudnn/cudnn_convolution-inl.h:155: Check failed: e == CUDNN_STATUS_SUCCESS (8 vs. 0) : cuDNN: CUDNN_STATUS_EXECUTION_FAILED
> > Stack trace:
> >   [bt] (0) /miniconda/envs/LRface/lib/python3.7/site-packages/mxnet/libmxnet.so(+0x6b41eb) [0x7f73e04301eb]
> >   [bt] (1) /miniconda/envs/LRface/lib/python3.7/site-packages/mxnet/libmxnet.so(+0x459d9bb) [0x7f73e43199bb]
> >   [bt] (2) /miniconda/envs/LRface/lib/python3.7/site-packages/mxnet/libmxnet.so(+0x45c6a59) [0x7f73e4342a59]
> >   [bt] (3) /miniconda/envs/LRface/lib/python3.7/site-packages/mxnet/libmxnet.so(+0x37d69b9) [0x7f73e35529b9]
> >   [bt] (4) /miniconda/envs/LRface/lib/python3.7/site-packages/mxnet/libmxnet.so(+0x37e333a) [0x7f73e355f33a]
> >   [bt] (5) /miniconda/envs/LRface/lib/python3.7/site-packages/mxnet/libmxnet.so(+0x37bf6d1) [0x7f73e353b6d1]
> >   [bt] (6) /miniconda/envs/LRface/lib/python3.7/site-packages/mxnet/libmxnet.so(+0x37c2c10) [0x7f73e353ec10]
> >   [bt] (7) /miniconda/envs/LRface/lib/python3.7/site-packages/mxnet/libmxnet.so(+0x37c2ea6) [0x7f73e353eea6]
> >   [bt] (8) /miniconda/envs/LRface/lib/python3.7/site-packages/mxnet/libmxnet.so(+0x37bde84) [0x7f73e3539e84]
> > ```
> 
> Possibly relevant: I have an RTX 2070 GPU, so I'm not sure if MXNet supports this already? Maybe not, as this seems to be an outdated MXNet version that requires Cuda 9.
> 
> Do you have access to the DGX station Andrea? If so, could you try running your docker container there?

Yes it could be, the Insight repo says that they use Tesla M40 GPU and the one I am using is GeForce GTX 1050Ti. I am going to see if I can get a Cuda image 10 running with mxnet-cu100 instead of 90.

No I don't have access to DGX station, can I without token? How could I get it? Should I ask FIG about it?

**Pull request closed without merging**
